### ISSUE TITLE
Lots of Scrollbars in Win 8.1 / Chrome

### ISSUE THREAD

**Issue by mrwweb** [UseriumUX/userium#8]
Logged in this morning and saw horiz and vert scrollbars on every list item:

![userium_scrollbars](https://cloud.githubusercontent.com/assets/1238696/6372186/11c03904-bcb7-11e4-88ce-bdca37792b1a.png)

Looks like an overflow issue.

**Comment by userium** [comment]
That's bad! Many thanks for finding this bug. We will fix this.

**Comment by userium** [comment]
We took away the overflow scroll, should work now, will test soon.

**Comment by userium** [comment]
We tested it, seems to work now on Windows 10 and Chrome. Thanks again for reporting this issue!
