### ISSUE TITLE
Mobile Horizontal scrolling.

### ISSUE THREAD

**Issue by iamlukem** [UseriumUX/userium#9]
The content is not centred on iPhone 5s as the content seems too wide for the display. 
adding "width: 100%;" to the &lt;div class="box tilava poista item kok masonry-brick" ... &gt;  and &lt;div id="masonry-container" .... &gt; seems to fix it. Obviously will have to be media queried in. 

Currently
![currently](https://cloud.githubusercontent.com/assets/3732162/6456545/c8eceab2-c1b9-11e4-8266-287993d1ceb6.png)

With Suggestion
![with suggestion](https://cloud.githubusercontent.com/assets/3732162/6456546/ccb28b02-c1b9-11e4-8bdd-d7698f2a5302.png)

**Comment by UseriumUX** [comment]
Thanks for this, Luke! We fixed it now!
